### ISSUE TITLE
Reconfigure git/ssh in Docker image

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux-lsp#176]
There's a CircleCI job called `deploy` that runs whenever it detects a commit tag that starts with `v` (e.g., `v0.5.2`). Right now, it fails with the following output:

```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
Enumerating objects: 54, done.
Counting objects: 100% (54/54), done.
Compressing objects: 100% (41/41), done.
Total 1281 (delta 18), reused 31 (delta 9), pack-reused 1227

object not found
```

This job is a potentially useful contribution toward #171. We should address this error so that we can reliably use this CI job to publish to NPM for us.

**Comment by scbrickley** [comment]
Link to failed job for reference: https://app.circleci.com/pipelines/github/influxdata/flux-lsp/346/workflows/22c925f0-9bb8-4dad-b2b2-7a062027f449/jobs/904

**Comment by nathanielc** [comment]
@scbrickley A possible fix to this one could be to install `git` into the `quay.io/influxdb/wasm-build` image. Adding it to this list is probably enough https://github.com/influxdata/flux-lsp/blob/master/Dockerfile#L16
