### ISSUE TITLE
LSP shuts down after encountering error in Cloud 2 UI

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux-lsp#190]
When typing out the following, without using autocomplete:

```
from(bucket: )
```

The LSP reports a `missing property value` error. Even after providing a bucket name, autocomplete stops working. This appears to only be a problem with the Cloud 2.0 UI.

**Comment by scbrickley** [comment]
Looks like this is not a problem with OSS 2.0 - It occurs only in the Cloud 2.0 UI.

**Comment by scbrickley** [comment]
An update on what I've found so far:

The LSP occassionally needs to request user data (in this case, I've only been able to reproduce the error when trying to get bucket names). If everything is running locally, there's no issue, but if that request needs to be made over a network, and it takes too long to resolve, the LSP has a tantrum and stops working.

To reproduce the error, open up the script editor in OSS. Then, throttle your network connection in dev tools. Type the following into the editor *without using autocomplete.*

```
from(bucket:)
```

Upon typing the `:` character, the console should log the error `Uncaught (in promise) Error: undefined`. This should coincide with a network request made to `http://localhost:8086/api/v2/buckets?orgID=<someID>&limit=100`.

The problem appears to be with [this line](https://github.com/influxdata/flux-lsp/blob/e378cb3233a54af77006c7fdd18d55157f2ae5e3/src/shared/callbacks.rs#L202), which is `await`ing a value to return from a [ `wasm_bidgen_futures::JsFuture` ](https://docs.rs/wasm-bindgen-futures/0.4.18/wasm_bindgen_futures/struct.JsFuture.html). The panic appears to happen before the future ever has a chance to resolve.

Still working out why this only happens when you don't use autocomplete. It has something to do with the fact that actually typing `:` triggers a separate [path of execution](https://github.com/influxdata/flux-lsp/blob/e378cb3233a54af77006c7fdd18d55157f2ae5e3/src/handlers/completion.rs#L726) than whatever's happening when using autocomplete to type out `bucket`.

**Comment by scbrickley** [comment]
Another update:

Upon further investigation, @nathanielc and I found this in the documentation for `wasm_bindgen_futures::JsFuture`:

```
/// Note that in wasm panics are currently translated to aborts, but "abort" in
/// this case means that a JavaScript exception is thrown. The wasm module is
/// still usable (likely erroneously) after Rust panics.
///
/// If the `future` provided panics then the returned `Promise` **will not
/// resolve**. Instead it will be a leaked promise. This is an unfortunate
/// limitation of wasm currently that's hoped to be fixed one day!
```

...which sounds an awful lot like what we're dealing with: an unresolved and leaked future/promise. So there must be a panic/abort going on somewhere. The problem is that there is no obvious area of code that causes a panic.

Some details:

The problem starts here. When reproducing the error as described in the comment above, this `get_buckets` function is called, but execution never makes it past the indicated line.

```rust
    pub async fn get_buckets(&self) -> Result<Vec<String>, String> {
        let mut finished = Resolvable::default();
        let mut cloned = finished.clone();
        let cln = self.clone();

        spawn_local(async move {
            let future = cln.call_buckets();
            match future {
                Ok(future) => {
                    if let Ok(returned) = future.await { // <---Panic/abort happens here
                        if let Ok(v) = returned.into_serde() {
                            cloned.resolve(v);
                        } else {
                            cloned.resolve(vec![]);
                        }
                    } else {
                        cloned.resolve(vec![]);
                    }
                }
                Err(_) => cloned.resolve(vec![]),
            }
        });

        finished.clone().await;
        Ok(finished.result())
    }
```

If there was an error we could handle, we would expect one of the else blocks or a different match arm to trigger. Instead, the LSP seems to panic on the indicated line, and as a result, stops working completely.

It's important to note that the `call_buckets` function that's giving us this `JsFuture` value is just a wrapper around another function call that's defined outside of the LSP codebase. Consumers of the LSP are expected to register their own functions to act as callbacks to fetch user data (i.e. buckets, mesaurements, tag keys & values). The various `register_callback` are defined [ here ](https://github.com/influxdata/flux-lsp/blob/e378cb3233a54af77006c7fdd18d55157f2ae5e3/src/shared/callbacks.rs#L130-L145).

In the 2.0 UI, we register the `buckets` callback [here](https://github.com/influxdata/influxdb/blob/bac5515a0a64a64c7f5ca6c83b3b50c6bb355b51/ui/src/external/monaco.flux.server.ts#L123) and pass in the [ `getBuckets` ](https://github.com/influxdata/influxdb/blob/bac5515a0a64a64c7f5ca6c83b3b50c6bb355b51/ui/src/external/monaco.flux.server.ts#L152-L162) function.

As far as we can tell, the call to `getBuckets` completes successfully, *even when reproducing the error*.

Since there does not appear to be any panic/abort in either the Rust code for the LSP or the JavaScript code for the UI, we should investigate whether or not the problem has to do with the WASM tooling itself. Upgrading to the most recent version of `wasm_bindgen` and all of its associated crates does not appear to solve the problem.

**Comment by scbrickley** [comment]
There aren't a lot of details provided, but it's possible this issue is related: https://github.com/rustwasm/wasm-bindgen/issues/2329

**Comment by scbrickley** [comment]
Older version of this issue: https://github.com/influxdata/influxdb/issues/18638

**Comment by scbrickley** [comment]
After failing to reproduce the issue with just the `wasm-bindgen` tools, @nathanielc and I decided to disable the problematic callbacks until a better, more permanent solution can be found. This means autocomplete for user-specific data will not be available until these callbacks are re-enabled. See #194 for details.

We suspect the cause of the issue was an [ill-advised implementation of the `Send` and `Sync` traits on the `Callback` type](https://github.com/influxdata/flux-lsp/blob/3dd787883f25329e3ead7ad672df58514f4039cc/src/shared/callbacks.rs#L119-L120). The Callback generates a JsFuture, which contains an `Rc<RefCell<_>`. As explained in [the Rustonomicon](https://doc.rust-lang.org/beta/nomicon/send-and-sync.html), types containing `Rc` and `Cell/RefCell` are not thread safe. This is normally the kind of error you'd expect the Rust compiler to catch, but because implementing the `Send` and `Sync` traits can only be done using an `unsafe` block, there are no checks on it. It was difficult to get a transparent error message, so we can't confirm this at the moment, but this is the best available lead.

In any case, the `Callback` type needs to implement `Send` and `Sync` in order for the LSP to work as designed, so there isn't much we can do without a much larger refactor. There should be an epic built around this at some point in the future.

**Comment by nathanielc** [comment]
For now we have disabled dynamic auto-completion so as to avoid this bug. We will come back to the root cause of this issue later.

**Comment by scbrickley** [comment]
Note: disabling the callbacks has led to issue #197

**Comment by rockstar** [comment]
I can confirm that the `lspower`-based server has much fewer edge cases where things panic and break. That's good news. However, this new server also uses `unwrap` a lot, and each one of those instance is a case where we potentially have a crash. I think it might be prudent to find a way for the client side to detect those crashes and kill the wasm environment and re-create it. The only way I can currently think of is to send check-in messages to the server regularly (maybe `initialized`) with a timeout and if the timeout is ever exceeded, we know the server isn't responding (the way it crashes is to just stop responding to requests).

**Comment by rockstar** [comment]
As of `0.6.11`, we catch panics that come out of those calls and return them as errors, so we aren't left in tho bad state. As well, `unwrap` is now disallowed via `clippy::unwrap`, so we should have narrowed the scope of where things _could_ panic and then caught the panic. Going further, if there are panics, we now have hooks in place to get information the console about the error, including stack traces, so more specific bugs can be filed. I'm not sure there's much more we can do to address this bug now.
