### ISSUE TITLE
Document how to stand up the LSP in a new environment

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux-lsp#216]
Currently, there is no documentation for how the LSP works, or how to incorporate it into other text editors. We should cut our teeth on setting up the LSP in a new environment, and document the steps necessary to do so.

Additionally, this should _only_ document the new rust-based lsp command, where appropriate. The node-based wasm shim should be considered EOL when `lsp2` becomes the default as part of #288.

DOD:

- A document (perhaps the README?) exists for running the lsp server.
- [The vim/flux-lsp documentation](https://docs.influxdata.com/influxdb/v2.0/tools/flux-vim-lsp/) is updated to reflect the rust-based command line lsp.

**Comment by idclark** [comment]
@scbrickley I'm in the earliest stages of thinking about how to integrate `flux-lsp` into the emacs-lsp ecosystem- to the best of my knowledge no one (internal or external to Influx) has attempted that yet. Is this something we could collaborate on?

**Comment by scbrickley** [comment]
@idclark Possibly. I think @pierwill suggested doing something similar not too long ago as a hackathon project.

We're currently working on plans to address some outstanding technical debt in the LSP, and that may take a while. Once that's done, I think we can start considering integration into other text editors.

**Comment by weidaolee** [comment]
@idclark @scbrickley hi guys! All my current projects use emacs to edit code, except for flux files. I very much hope that `flux-lsp` can be integrated into the emacs ecosystem. Currently, the emacs ecosystem lacks `flux-mode`, `flux-company`, and integration with `flux-lsp`. I wonder if there has been any progress in this demand in the past two years?
