### ISSUE TITLE
Spike: implement bare-bones flux lsp using lspower crate

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux-lsp#224]
Before we do a full refactor of the LSP, we should cut our teeth on standing up a minimal flux lsp using the [`lspower`](https://github.com/silvanshade/lspower) crate.

DOD:
- We have a language server implemented using the `lspower` crate that can send messages to and receive messages from a javascript-based text editing client

**Comment by rockstar** [comment]
This has been completed.
