### ISSUE TITLE
Implement completion handlers in lspower server

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux-lsp#239]
Once we have the `lspower` stub from #224 we should implement handlers for auto-completion according to the LSP spec. We need to support two requests for this to work:

- [`textDocument/completion`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion) to send a list of completion suggestions to the client.
- [`completionItem/resolve`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#completionItem_resolve) to update the document with the completion item chosen by the user.

Our current implementations of these handlers can be found here:
- [`completion`](https://github.com/influxdata/flux-lsp/blob/master/src/handlers/completion.rs)
- [`completion_resolve`](https://github.com/influxdata/flux-lsp/blob/master/src/handlers/completion_resolve.rs)

While we're at it, it would be nice to see if we can re-enable bucket name completions with the new LSP implementation, along with other user-specific completables, which were disabled in https://github.com/influxdata/flux-lsp/pull/194

**Comment by russorat** [comment]
it would be nice to add autocomplete for secrets when using `secrets.get(key: "")` if we can.

**Comment by rockstar** [comment]
> it would be nice to add autocomplete for secrets when using secrets.get(key: "") if we can.

I would prefer we keep this issue to just porting what's there and working already. Please feel free to file an issue so we don't forget to address it when we build out the completions a bit more.
