### ISSUE TITLE
Implement hover request handler in lspower server

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux-lsp#240]
Once we have the lspower stub from #224, we should implement a handler for hover requests, according to the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_hover).

For reference, our current implementation is [here](https://github.com/influxdata/flux-lsp/blob/master/src/handlers/hover.rs).

**Comment by rockstar** [comment]
This was actually never actually implemented in the old server. The server _claims_ to support it in initialization capabilities, but it always just returns an empty response no matter what. This can't be ported over, but should be implemented when we go through and add features.
