### ISSUE TITLE
Map parse errors to diagnostic notifications in the new server implementation.

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux-lsp#290]
The old LSP could convert parse errors into diagnostic notifications and still respond to completion requests. It appears the new implementation can't handle that quite yet. We will need to find a way to adapt the [`map_errors_to_diagnostics()`](https://github.com/influxdata/flux-lsp/blob/22bab60686212d8d5ca797d39bc6cf18d3bb36ca/src/shared/conversion.rs#L23) logic to the new server in order to fix that.

There was one test that failed because of this. It has now been modified slightly to get it to pass, but it should be reverted back once this is fixed: https://github.com/influxdata/flux-lsp/blob/6cd5080dc8105756fd469f62fa27697d6c24ec49/src/server.rs#L1823

**Comment by rockstar** [comment]
Just tested this out on a branch and this is no longer occurring. The comment describing the issue has been removed in a WIP branch.
