### ISSUE TITLE
TestCase is not supported in semantic analysis

### ISSUE THREAD

**Issue by onelson** [influxdata/flux-lsp#403]
When using the CLI lang server with IntelliJ, testcases are rendered as errors.

![image](https://user-images.githubusercontent.com/301388/154336341-d28d61ae-49d8-4258-8099-c36e025fdc2f.png)

For this instance, I was looking at `stdlib/array/array_test.flux` in the flux repo.
Here's the log output from the lang server:

```
[Trace - 10:52:12 AM] Sending notification 'textDocument/didChange'
Params: {
  "textDocument": {
    "version": 2,
    "uri": "file:///home/onelson/Projects/flux/stdlib/array/array_test.flux"
  },
  "contentChanges": [
    {
      "text": "package array_test\n\n\nimport \"testing\"\nimport \"array\"\n\nfromElement \u003d (v) \u003d\u003e array.from(rows: [{v: v}])\n\ntestcase fromElementTest {\n    want \u003d fromElement(v: 123)\n    got \u003d fromElemen
t(v: 123)\n\n    testing.diff(want, got)\n        |\u003e yield()\n}\n"
    }
  ]
}


[Trace - 10:52:12 AM] Received notification 'textDocument/publishDiagnostics'
Params: {
  "uri": "file:///home/onelson/Projects/flux/stdlib/array/array_test.flux",
  "diagnostics": [
    {
      "range": {
        "start": {
          "line": 8,
          "character": 0
        },
        "end": {
          "line": 14,
          "character": 1
        }
      },
      "severity": 1,
      "source": "flux",
      "message": "TestCase is not supported in semantic analysis"
    }
  ]
}
```

**Comment by onelson** [comment]
Coincidentally, this has the same treatment in vscode. It wasn't unexpected, but I didn't want to assume...
![Screenshot_20220216_114937](https://user-images.githubusercontent.com/301388/154344511-a3f850a7-ceff-4db3-9709-0b47cfd435b9.png)

**Comment by nathanielc** [comment]
I get this too, in short the test harness rewrites `testcase` AST into other AST statements removing the testcase statement. As a result semantic analysis doesn't know how to handle testcase statements.
