### ISSUE TITLE
Research integration with Atom

### ISSUE THREAD

**Issue by bthesorceror** [influxdata/flux-lsp#8]
Investigate what will be needed for integrating the lsp server with Atom.

**Comment by rockstar** [comment]
I think this is about as straightforward as VSCode's extension process is. [Github wrote a good intro blog post](https://github.blog/2016-08-19-building-your-first-atom-plugin/) and it appears that there's [an Atom languageclient](https://github.com/atom-community/atom-languageclient) that can be used.

While I think it's good to capture that here, I don't think building and maintaining an Atom plugin is the best use of our time, for now.
