### ISSUE TITLE
Add addition details to completions

### ISSUE THREAD

**Issue by bthesorceror** [influxdata/flux-lsp#82]
e.g. function signature for fuctions

**Comment by jademcgough** [comment]
We'd like to add doc comments from the core flux library - but don't think this is possible right now based off of the rest of the information provided from the flux library.

**Comment by bthesorceror** [comment]
We could work with the docs team on this and pull from an external source (i.e. the docs site). However this should be behind a flag as some people might not want the LSP making requests

**Comment by rockstar** [comment]
`textDocument/signatureHelp` is a more appropriate place for function signature information.
