### ISSUE TITLE
Add rustfmt in CI

### ISSUE THREAD

**Issue by kelwang** [influxdata/flux-lsp#83]
use the nightly version 
https://crates.io/crates/rustfmt-nightly, since https://crates.io/crates/rustfmt

command ```cargo +nightly fmt```

**Comment by bthesorceror** [comment]
why use the nightly over stable?

**Comment by kelwang** [comment]
> why use the nightly over stable?
> 
> does this give us anything that clippy doesn't?
> 
> Also we need to make sure that rustfmt isn't modifying code on CI `cargo fmt -- --check`

they screw up the name a little bit. the nightly actually the active maintained one. the other one is deprecated long time ago. 
clippy won't do the fmt. 
yeah, let's do the -- --check.
